modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/better-than-dirt/issues" #optional

[[mods]] #mandatory

modId="betterthandirt" #mandatory

version="1.15.2-1.0.1.5" #mandatory

displayName="Better Than Dirt" #mandatory

#updateJSONURL="" #optional

#displayURL="" #optional

logoFile="btdlogo.png" #optional

credits="To all the lovely poeple on the Forge Project Discord for their help." #optional

authors="cooperg2001" #optional

description='''
Better Than Dirt. Adds lots of fun armors.
'''

[[dependencies.betterthandirt]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.betterthandirt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"